use wasmtime::component::Linker;
use wasmtime::component::bindgen;

pub mod analog;
pub mod ctx;
pub mod delay;
pub mod digital;
pub mod general;
pub mod impls;
pub mod policies;
pub mod poll;
pub mod util;
pub mod watch_event;

pub use ctx::{GpioBindingMarker, WasiGpioCtx, WasiGpioView};
use impls::GpioImpl;

wasmtime::component::bindgen!({
    path: "../wit",
    world: "rpi",
    with: {
        "wasi:gpio/digital/digital-out-pin": crate::DigitalOutPin,
        "wasi:gpio/digital/digital-in-pin": crate::DigitalInPin,
        "wasi:gpio/digital/digital-in-out-pin": crate::DigitalInOutPin,
        "wasi:gpio/digital/stateful-digital-out-pin": crate::StatefulDigitalOutPin,
        "wasi:gpio/analog/analog-in-pin": crate::AnalogInPin,
        "wasi:gpio/analog/analog-out-pin": crate::AnalogOutPin,
        "wasi:gpio/analog/analog-in-out-pin": crate::AnalogInOutPin,
        "wasi:gpio/poll/pollable": crate::Pollable,
        "wasi:gpio/delay/delay": crate::Delay
    }
});

pub fn add_to_linker<T>(linker: &mut Linker<T>) -> anyhow::Result<()>
where
    T: WasiGpioView + 'static,
{
    // Note: The path to these modules is generated by bindgen, so we use the
    // paths exposed by the `wasi` module it generates.
    wasi::gpio::delay::add_to_linker::<T, GpioBindingMarker<T>>(linker, |host| GpioImpl { host })?;
    wasi::gpio::general::add_to_linker::<T, GpioBindingMarker<T>>(linker, |host| GpioImpl {
        host,
    })?;
    wasi::gpio::poll::add_to_linker::<T, GpioBindingMarker<T>>(linker, |host| GpioImpl { host })?;
    wasi::gpio::digital::add_to_linker::<T, GpioBindingMarker<T>>(linker, |host| GpioImpl {
        host,
    })?;
    wasi::gpio::analog::add_to_linker::<T, GpioBindingMarker<T>>(linker, |host| GpioImpl { host })?;
    Ok(())
}
